# fly.toml app configuration file generated for do-i-leak-referer on 2023-05-27T18:45:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "do-i-leak-referer"

primary_region = "ams"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  port = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
